- type: playTimeTracker
  id: JobPraefect

- type: playTimeTracker
  id: JobArbiter

- type: playTimeTracker
  id: JobCardinal

- type: playTimeTracker
  id: JobInquisitor

- type: playTimeTracker
  id: JobConsul

- type: playTimeTracker
  id: JobPraetorian

- type: playTimeTracker
  id: JobAuxilia

- type: playTimeTracker
  id: JobNeophyte

#region Renegates

- type: playTimeTracker
  id: JobBaron

- type: playTimeTracker
  id: JobDraftsman

- type: playTimeTracker
  id: JobOverseer

- type: playTimeTracker
  id: JobQuack

- type: playTimeTracker
  id: JobForeman

- type: playTimeTracker
  id: JobFlunky

# region Federation

- type: playTimeTracker
  id: JobTsfCommandingOfficer

- type: playTimeTracker
  id: JobTsfExecutiveOfficer

- type: playTimeTracker
  id: JobTsfSeniorOfficer

- type: playTimeTracker
  id: JobTsfSeniorAide

- type: playTimeTracker
  id: JobTsfRanger

- type: playTimeTracker
  id: JobTsfRecruit

- type: playTimeTracker
  id: JobTsfAmbassador

- type: playTimeTracker
  id: JobTsfMedic

- type: playTimeTracker
  id: JobTsfsl

- type: playTimeTracker
  id: JobTsfCrew

- type: playTimeTracker
  id: JobTsfCrewOfficer

# region NanoTrasen
- type: playTimeTracker
  id: NtMedic

- type: playTimeTracker
  id: NtMedicPilot

- type: playTimeTracker
  id: NtMedicGunner

- type: playTimeTracker
  id: JobNtScientist

- type: playTimeTracker
  id: JobNtEngineer

- type: playTimeTracker
  id: JobNtBotanist

- type: playTimeTracker
  id: JobNtCook
