- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/_Forge/Guidebook/Security/Security.xml" # Forge-change
  children:
  - Forensics
  - Defusal
  - CriminalRecords
#  - SpaceLaw # Frontier - irrelevant
  - Smuggling # Frontier

- type: guideEntry
  id: Forensics
  name: guide-entry-forensics
  text: "/ServerInfo/_Forge/Guidebook/Security/Forensics.xml" # Forge-change

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/_Forge/Guidebook/Security/Defusal.xml" # Forge-change

- type: guideEntry
  id: CriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/_Forge/Guidebook/Security/CriminalRecords.xml" # Forge-change

# Frontier: not our lawset, shouldn't show up
# - type: guideEntry
#   id: SpaceLaw
#   name: guide-entry-rules-space-law
#   text: "/ServerInfo/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml"
#   children:
#   - SpaceLawCrimeList

# - type: guideEntry
#   id: SpaceLawCrimeList
#   name: guide-entry-rules-sl-crime-list
#   text: "/ServerInfo/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml"
# End Frontier
