- type: guideEntry
  id: Service
  name: guide-entry-service
  text: "/ServerInfo/_Forge/Guidebook/Service/Service.xml" # Forge-change
  filterEnabled: True
  children:
  - Bartender
  - Botany
  - Chef
  - Janitorial

- type: guideEntry
  id: Bartender
  name: guide-entry-bartender
  text: "/ServerInfo/_Forge/Guidebook/Service/Bartender.xml" # Forge-change
  filterEnabled: True

- type: guideEntry
  id: Botany
  name: guide-entry-botany
  text: "/ServerInfo/_Forge/Guidebook/Service/Botany.xml" # Forge-change

- type: guideEntry
  id: Chef
  name: guide-entry-chef
  text: "/ServerInfo/_Forge/Guidebook/Service/Chef.xml" # Forge-change

- type: guideEntry
  id: Janitorial
  name: guide-entry-janitorial
  text: "/ServerInfo/_Forge/Guidebook/Service/Janitorial.xml" # Forge-change
