- type: job
  id: TsfMedic
  name: job-name-tsf-medic
  description: job-description-tsf-Medic
  playTimeTracker: JobTsfMedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000
    - !type:RoleTimeRequirement
      role: JobTsfRecruit
      time: 18000
  setPreference: false
  overrideConsoleVisibility: true
  startingGear: TsfMedicGear
  icon: JobIconBrigmedicNF
  supervisors: job-supervisors-tsf-officers
  weight: 130
  displayWeight: 40
  assignedCompany: TSF
  canBeAntag: false
 # guides: [ BasicLore, TransSolarFederation ] # Forge-Change-delete
  accessGroups:
  - TsfGeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfMedicGear
