- type: job
  id: TsfRecruit
  name: job-name-tsf-recruit
  description: job-description-tsf-recruit
  playTimeTracker: JobTsfRecruit
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 32400
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000
      inverted: true
  startingGear: TsfRecruitGear
  icon: JobIconTsfRecruit
  supervisors: job-supervisors-tsf-rangers
  weight: 70
  displayWeight: 10
  assignedCompany: TSF
  canBeAntag: false
 # guides: [ BasicLore, TransSolarFederation ] # Forge-Change-delete
  accessGroups:
  - TsfCadetAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfRecruitGear
  equipment:
    pocket1: WeaponPistolMk58
    pocket2: BookSecurity
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - FederationMilitaryCredit50
    - BaseSecurityUplinkRadio
    - RadioHandheldNF
