- type: job
  id: TsfSeniorOfficer
  name: job-name-tsf-senior-officer
  description: job-description-tsf-senior-officer
  playTimeTracker: JobTsfSeniorOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 28800
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000
  startingGear: TsfSeniorOfficerGear
  icon: JobIconTsfSeniorOfficer
  supervisors: job-supervisors-tsf-commanding-officer
  weight: 140
  displayWeight: 50
  assignedCompany: TSF
  canBeAntag: false
 # guides: [ BasicLore, TransSolarFederation ] # Forge-Change-delete
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Medical
  - Chemistry
  - TsfmcEngineering
  accessGroups:
  - TsfGeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfSeniorOfficerGear
  equipment:
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioOfficer
    - RadioHandheldNF
