using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Forge.Crypto.Components;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using System.Linq;

namespace Content.Client._Forge.Crypto.UI;

[GenerateTypedNameReferences]
public sealed partial class CryptoSellConsoleWindow : FancyWindow
{
    private readonly List<string> _marketOrder = new();
    private Dictionary<string, CryptoMarketUiData> _marketData = new();

    public CryptoSellConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        MarketTabs.OnTabChanged += OnTabChanged;
        MarketTabs.SetTabTitle(0, Loc.GetString("crypto-console-tab-contribcoin"));
        MarketTabs.SetTabTitle(1, Loc.GetString("crypto-console-tab-ideascoin"));
        MarketTabs.SetTabTitle(2, Loc.GetString("crypto-console-tab-corvaxcoin"));
        _marketOrder.AddRange(["contribcoin", "ideascoin", "corvaxcoin"]);
    }

    public void UpdateState(CryptoSellConsoleBoundUserInterfaceState state)
    {
        _marketData = state.Markets.ToDictionary(m => m.MarketId, m => m);

        InsertedValueLabel.Text = state.HasBitcoin
            ? Loc.GetString("crypto-console-inserted-value", ("name", state.InsertedName), ("count", state.InsertedUnits))
            : Loc.GetString("crypto-console-inserted-none-value");
        UnitsValueLabel.Text = state.InsertedUnits.ToString("N0");
        PreviewValueLabel.Text = Loc.GetString("crypto-console-value-credits", ("value", state.PreviewPayout.ToString("N0")));

        SellButton.Disabled = !state.HasBitcoin || state.InsertedUnits <= 0;
        EjectButton.Disabled = !state.HasBitcoin;

        RenderSelectedMarket();
        UpdateBuyRow();
    }

    private void OnTabChanged(int tabIndex)
    {
        // Redraw with currently cached market data.
        RenderSelectedMarket();
        UpdateBuyRow();
    }

    private void UpdateBuyRow()
    {
        var selected = GetSelectedMarket();
        if (selected is null)
        {
            BuyOneCostValueLabel.Text = Loc.GetString("crypto-console-value-empty");
            BuyOneButton.Disabled = true;
            return;
        }

        BuyOneCostValueLabel.Text = Loc.GetString("crypto-console-value-credits", ("value", selected.BuyOneUnitCost.ToString("N0")));
        BuyOneButton.Disabled = selected.BuyOneUnitCost <= 0;
    }

    private void RenderSelectedMarket()
    {
        var selectedMarket = GetSelectedMarket();
        if (selectedMarket is null)
        {
            CurrentPriceValueLabel.Text = Loc.GetString("crypto-console-value-empty");
            TrendValueLabel.Text = Loc.GetString("crypto-console-trend-no-data");
            HistoryGraph.SetPoints(Array.Empty<double>());
            HistoryRangeLabel.Text = Loc.GetString("crypto-console-range-empty");
            SetValueColors(Color.White, Color.White, Color.White, Color.White, Color.White);
            return;
        }

        CurrentPriceValueLabel.Text = Loc.GetString("crypto-console-value-credits-unit", ("value", Math.Round(selectedMarket.CurrentPrice).ToString("N0")));

        if (selectedMarket.PriceHistory.Count < 2)
        {
            TrendValueLabel.Text = Loc.GetString("crypto-console-trend-no-data");
            HistoryGraph.SetPoints(Array.Empty<double>());
            HistoryRangeLabel.Text = Loc.GetString("crypto-console-range-empty");
            SetValueColors(Color.White, Color.White, Color.White, Color.White, Color.White);
            return;
        }

        var first = selectedMarket.PriceHistory[0];
        var last = selectedMarket.PriceHistory[^1];
        var delta = last - first;
        var trend = delta switch
        {
            > 0.5 => Loc.GetString("crypto-console-trend-rising", ("delta", Math.Round(delta).ToString("N0"))),
            < -0.5 => Loc.GetString("crypto-console-trend-falling", ("delta", Math.Round(delta).ToString("N0"))),
            _ => Loc.GetString("crypto-console-trend-stable")
        };

        TrendValueLabel.Text = trend;

        var min = selectedMarket.PriceHistory.Min();
        var max = selectedMarket.PriceHistory.Max();
        HistoryRangeLabel.Text = Loc.GetString("crypto-console-range-value",
            ("min", Math.Round(min).ToString("N0")),
            ("max", Math.Round(max).ToString("N0")));
        HistoryGraph.SetPoints(selectedMarket.PriceHistory);

        var trendColor = delta switch
        {
            > 0.5 => Color.LimeGreen,
            < -0.5 => Color.IndianRed,
            _ => Color.White
        };
        SetValueColors(Color.LimeGreen, trendColor, Color.White, Color.LimeGreen, Color.Cyan);
    }

    private CryptoMarketUiData? GetSelectedMarket()
    {
        if (_marketOrder.Count == 0)
            return null;

        var tab = Math.Clamp(MarketTabs.CurrentTab, 0, _marketOrder.Count - 1);
        var marketId = _marketOrder[tab];
        return _marketData.GetValueOrDefault(marketId);
    }

    /// <summary>Market id for the active tab (e.g. contribcoin), for server purchase requests.</summary>
    public string? GetSelectedMarketId()
    {
        if (_marketOrder.Count == 0)
            return null;

        var tab = Math.Clamp(MarketTabs.CurrentTab, 0, _marketOrder.Count - 1);
        return _marketOrder[tab];
    }

    private void SetValueColors(Color price, Color trend, Color inserted, Color payout, Color buy)
    {
        CurrentPriceValueLabel.Modulate = price;
        TrendValueLabel.Modulate = trend;
        InsertedValueLabel.Modulate = inserted;
        UnitsValueLabel.Modulate = inserted;
        PreviewValueLabel.Modulate = payout;
        BuyOneCostValueLabel.Modulate = buy;
    }
}
