using Content.Client._Forge.Company.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.Company;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

// Forge-Change-full: company whitelist
namespace Content.Client.Lobby.UI.Company;

[GenerateTypedNameReferences]
public sealed partial class CompanyWindow : FancyWindow
{
    public event Action<string>? OnCompanySelected;

    public CompanyWindow()
    {
        RobustXamlLoader.Load(this);
        CompanySelect.OnCompanySelected += id => OnCompanySelected?.Invoke(id);
    }

    public void Populate(List<CompanyPrototype> companies, HashSet<string> selectableCompanyIds, string? currentCompanyId)
    {
        CompanySelect.Populate(companies, selectableCompanyIds, currentCompanyId);
    }
}
