- type: job
  id: StationRepresentative
  name: job-name-sr
  description: job-description-sr
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs, forge
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 21600 # 6 hrs, forge
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 # 6 hours, forge
    - !type:RoleTimeRequirement
      role: JobStc
      time: 7200 # 2 hrs, forge
    - !type:RoleTimeRequirement
      role: JobCCServiceWorker
      time: 7200 # 2 hrs, forge
  startingGear: SrGear
  alwaysUseSpawner: true
  assignedCompany: Colonial
  icon: "JobIconSr" # Forge
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 60 # Forge
  canBeAntag: false
  accessGroups:
  - AllAccessSR
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Mono - remove TSFMC implant
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      #- type: NpcFactionMember - Commented out to seperate them from TSFMC.
      #  factions:
      #  - TSFMC
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SrGear
  equipment:
    pocket1: WeaponEnergyGunLawbringer
  storage:
    back:
    - Flash
    - RubberStampSr
    - DoorRemoteCommand
#    - EncryptionKeyCentCom # Forge-Change-Remove
    - EncryptionKeyStationMasterSR #Mono start
    - EncryptionKeyDiplomacy
    - EncryptionKeyHospital # Forge
    - ShipVoucherFrontierGuard
    - PhoneInstrumentHigh
