using JetBrains.Annotations;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

// Forge-Change-full: whitelist
namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class WhitelistAccessWindow : DefaultWindow
{
    private PlayerInfo? _selectedPlayer;

    public WhitelistAccessWindow()
    {
        RobustXamlLoader.Load(this);

        PlayerList.OnSelectionChanged += OnSelectionChanged;
        OpenWhitelistsButton.OnPressed += OnOpenPressed;
    }

    private void OnSelectionChanged(PlayerInfo? player)
    {
        _selectedPlayer = player;
        OpenWhitelistsButton.Disabled = _selectedPlayer == null;
    }

    private void OnOpenPressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedPlayer == null)
            return;

        IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"jobwhitelists \"{_selectedPlayer.SessionId}\"");
        Close();
    }
}
