- type: job
  id: Neophyte # Cadet
  name: forge-job-name-neophyte
  description: forge-job-desc-neophyte
  supervisors: job-supervisors-praetorian
  playTimeTracker: JobNeophyte
  icon: JobIconEmpireNeophyte
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours
    - !type:SpeciesRequirement
      inverted: true
      species:
        # - SlimePerson
        - Arachnid
        - Chitinid
        - Resomi
        - Vox
        - Diona
        - Goblin
        - Hydrakin
        - Vulpkanin
        # - Tajaran
        # - Reptilian
        # - Oni
        # - Moth
        # - IPC
  startingGear: NeophyteGear
  weight: 10
  displayWeight: 10
  canBeAntag: false
  setPreference: true
  assignedCompany: Imperial
  accessGroups:
  - GeneralEmpireAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Empire

- type: startingGear
  id: NeophyteGear
  # equipment:
  #   ears:
  #   belt:
  #   pocket1:
  #   pocket2:
  # storage:
  #   back:
  #   - RadioHandheldNF
