    # - !type:SpeciesRequirement
    #   inverted: true
    #   species:
    #     - Human
    #     - SlimePerson
    #     - Arachnid
    #     - Diona
    #     - Moth
    #     - Reptilian
    #     - Vox
    #     - Oni
    #     - Chitinid
    #     - Harpy
    #     - Rodentia
    #     - Vulpkanin
    #     - IPC
    #     - Resomi
    #     - Tajaran
    #     - Goblin
    #     - Hydrakin
