using Content.Shared._Mono.Company;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

// Forge-Change-full: company whitelist
namespace Content.Client._DV.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class CompanyWhitelistPanel : PanelContainer
{
    public Action<string, bool>? OnSetCompany;

    public CompanyWhitelistPanel(
        List<string> companies,
        string title,
        Color color,
        IPrototypeManager proto,
        HashSet<string> whitelists)
    {
        RobustXamlLoader.Load(this);

        var allWhitelisted = true;
        foreach (var id in companies)
        {
            if (!proto.TryIndex<CompanyPrototype>(id, out var company))
                continue;

            var thisCompany = id;
            var button = new CheckBox
            {
                Text = company.Name,
                Pressed = whitelists.Contains(id),
            };
            button.OnPressed += _ => OnButtonPressed(thisCompany, button);
            CompaniesContainer.AddChild(button);

            allWhitelisted &= button.Pressed;
        }

        CompaniesSet.Text = title;
        CompaniesSet.Modulate = color;
        CompaniesSet.Pressed = allWhitelisted;
        CompaniesSet.OnPressed += _ => OnSetPressed(companies, whitelists);
    }

    private void OnButtonPressed(string companyId, CheckBox button)
    {
        OnSetCompany?.Invoke(companyId, button.Pressed);
    }

    private void OnSetPressed(List<string> companies, HashSet<string> whitelists)
    {
        foreach (var id in companies)
        {
            if (whitelists.Contains(id) != CompaniesSet.Pressed)
                OnSetCompany?.Invoke(id, CompaniesSet.Pressed);
        }
    }
}
