using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Content.Shared._Mono.Company;
using Content.Client._Mono.Company;
using System.Linq;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Company.UI;

[GenerateTypedNameReferences]
public sealed partial class CompanySelectControl : BoxContainer
{
    [Dependency] private readonly CompanyManager _companyManager = default!;
    public event Action<string>? OnCompanySelected;

    private List<CompanyPrototype> _companies = new();
    private readonly Dictionary<string, Button> _companyButtons = new();
    private string? _selectedCompanyId;
    private string _currentCompanyId = "None";

    public CompanySelectControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        JoinCompanyButton.OnPressed += _ =>
        {
            if (string.IsNullOrEmpty(_selectedCompanyId))
                return;

            if (!_companyManager.IsAllowed(_selectedCompanyId))
                return;

            _currentCompanyId = _selectedCompanyId;
            OnCompanySelected?.Invoke(_selectedCompanyId);
            RefreshActions();
        };

        LeaveCompanyButton.OnPressed += _ =>
        {
            if (_currentCompanyId == "None")
                return;

            _currentCompanyId = "None";
            OnCompanySelected?.Invoke("None");
            RefreshActions();
        };
    }

    public void Populate(List<CompanyPrototype> companies, string? selectedCompanyId = null)
    {
        _companies = companies;
        _currentCompanyId = string.IsNullOrEmpty(selectedCompanyId) ? "None" : selectedCompanyId;
        _selectedCompanyId = _currentCompanyId;
        _companyButtons.Clear();

        CompanyListContainer.DisposeAllChildren();

        foreach (var company in _companies)
        {
            if (company.Hidden)
            continue;

            var companyId = company.ID;
            var button = new Button
            {
                Text = company.Name,
                HorizontalExpand = true,
            };

            button.OnPressed += _ =>
            {
                _selectedCompanyId = companyId;
                UpdateCompanyCard(companyId);
            };

            _companyButtons[companyId] = button;
            CompanyListContainer.AddChild(button);
        }

        if (_selectedCompanyId == null || !_companies.Any(c => c.ID == _selectedCompanyId))
        {
            _selectedCompanyId = _companies.FirstOrDefault()?.ID;
        }

        if (_selectedCompanyId != null)
        {
            UpdateCompanyCard(_selectedCompanyId);
        }
    }

    private void UpdateCompanyCard(string companyId)
    {
        var company = _companies.FirstOrDefault(c => c.ID == companyId);
        if (company == null)
            return;

        foreach (var (id, button) in _companyButtons)
        {
            button.Modulate = id == companyId ? Color.White : new Color(0.92f, 0.92f, 0.92f, 1f);
        }

        if (company.ID == "None")
        {
            CompanyDescriptionPanel.Visible = false;
            CompanyLockedStripe.Visible = false;
            RefreshActions();
            return;
        }

        CompanyDescriptionPanel.Visible = true;
        var isSelectable = _companyManager.IsAllowed(company.ID);
        CompanyLockedStripe.Visible = !isSelectable;

        var text = !string.IsNullOrEmpty(company.Description)
            ? Loc.GetString(company.Description)
            : Loc.GetString("company-none-description");

        CompanyDescription.SetMessage(FormattedMessage.FromMarkupPermissive(text));

        var note = !string.IsNullOrEmpty(company.Note)
            ? Loc.GetString(company.Note)
            : null;

        CompanyNotePanel.Visible = note != null;

        if (note != null)
        {
            CompanyNote.SetMessage(FormattedMessage.FromMarkupPermissive(note));
        }

        RefreshActions();
    }

    private void RefreshActions()
    {
        var selected = _selectedCompanyId;
        JoinCompanyButton.Disabled = string.IsNullOrEmpty(selected)
            || selected == "None"
            || selected == _currentCompanyId
            || !_companyManager.IsAllowed(selected);

        LeaveCompanyButton.Disabled = _currentCompanyId == "None";
    }
}
