using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Content.Shared._Mono.Company;
using System.Linq;
using Robust.Client.Player;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.Company.UI;

[GenerateTypedNameReferences]
public sealed partial class CompanySelectControl : BoxContainer
{
    public event Action<string>? OnCompanySelected;

    private List<CompanyPrototype> _companies = new();
    private string? _currentCompany;

    public CompanySelectControl()
    {
        RobustXamlLoader.Load(this);

        CompanyDropdown.OnItemSelected += args =>
        {
            if (args.Id < 0 || args.Id >= _companies.Count)
                return;

            CompanyDropdown.SelectId(args.Id);
            UpdateCompanyCard(args.Id);

            var companyId = _companies[args.Id].ID;
            _currentCompany = companyId;
            OnCompanySelected?.Invoke(companyId);
        };
    }

    public void Populate(List<CompanyPrototype> companies, string? selectedCompanyId = null)
    {
        var session = IoCManager.Resolve<IPlayerManager>().LocalPlayer;
        var playerLogin = session?.Name;

        _companies = companies
            .Where(c => c.Logins == null || c.Logins.Count == 0 || (playerLogin != null && c.Logins.Contains(playerLogin)))
            .ToList();

        CompanyDropdown.Clear();

        for (var i = 0; i < _companies.Count; i++)
        {
            CompanyDropdown.AddItem(_companies[i].Name, i);
        }

        int selectedIndex = 0;
        if (!string.IsNullOrEmpty(selectedCompanyId))
        {
            var found = _companies.FindIndex(c => c.ID == selectedCompanyId);
            if (found != -1)
                selectedIndex = found;
        }

        if (_companies.Count > 0)
        {
            CompanyDropdown.SelectId(selectedIndex);
            UpdateCompanyCard(selectedIndex);

            _currentCompany = _companies[selectedIndex].ID;
            OnCompanySelected?.Invoke(_currentCompany);
        }
    }

    private void UpdateCompanyCard(int index)
    {
        if (index < 0 || index >= _companies.Count)
            return;

        var company = _companies[index];

        if (company.ID == "None")
        {
            CompanyDescriptionPanel.Visible = false;
            CompanyImagePanel.Visible = false;
            return;
        }

        CompanyDescriptionPanel.Visible = true;
        CompanyImagePanel.Visible = true;

        var text = !string.IsNullOrEmpty(company.Description)
            ? Loc.GetString(company.Description)
            : Loc.GetString("company-none-description");

        CompanyDescription.SetMessage(text);

        if (company.EntityIcon != null)
        {
            CompanyImage.SetPrototype(company.EntityIcon.Value);
            CompanyImage.Visible = true;
        }
        else
        {
            CompanyImage.Visible = false;
        }
    }
}
