using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Content.Shared._Mono.Company;
using System.Linq;

namespace Content.Client._Forge.Company.UI;

[GenerateTypedNameReferences]
public sealed partial class CompanySelectControl : BoxContainer
{
    private static readonly Color AvailableTint = new(0.78f, 1.00f, 0.78f, 1.00f);
    private static readonly Color LockedTint = new(1.00f, 0.78f, 0.78f, 1.00f);

    public event Action<string>? OnCompanySelected;

    private List<CompanyPrototype> _companies = new();
    private HashSet<string> _selectableCompanyIds = new();
    private readonly Dictionary<string, Button> _companyButtons = new();
    private string? _selectedCompanyId;
    private string _currentCompanyId = "None";

    public CompanySelectControl()
    {
        RobustXamlLoader.Load(this);
        JoinCompanyButton.OnPressed += _ =>
        {
            if (string.IsNullOrEmpty(_selectedCompanyId))
                return;

            if (!_selectableCompanyIds.Contains(_selectedCompanyId))
                return;

            _currentCompanyId = _selectedCompanyId;
            OnCompanySelected?.Invoke(_selectedCompanyId);
            RefreshActions();
        };

        LeaveCompanyButton.OnPressed += _ =>
        {
            if (_currentCompanyId == "None")
                return;

            _currentCompanyId = "None";
            OnCompanySelected?.Invoke("None");
            RefreshActions();
        };
    }

    public void Populate(List<CompanyPrototype> companies, HashSet<string> selectableCompanyIds, string? selectedCompanyId = null)
    {
        _companies = companies;
        _selectableCompanyIds = selectableCompanyIds;
        _currentCompanyId = string.IsNullOrEmpty(selectedCompanyId) ? "None" : selectedCompanyId;
        _selectedCompanyId = _currentCompanyId;
        _companyButtons.Clear();

        CompanyListContainer.DisposeAllChildren();

        foreach (var company in _companies)
        {
            var companyId = company.ID;
            var button = new Button
            {
                Text = company.Name,
                HorizontalExpand = true,
            };

            button.OnPressed += _ =>
            {
                _selectedCompanyId = companyId;
                UpdateCompanyCard(companyId);
            };

            _companyButtons[companyId] = button;
            CompanyListContainer.AddChild(button);
        }

        if (_selectedCompanyId == null || !_companies.Any(c => c.ID == _selectedCompanyId))
        {
            _selectedCompanyId = _companies.FirstOrDefault()?.ID;
        }

        if (_selectedCompanyId != null)
        {
            UpdateCompanyCard(_selectedCompanyId);
        }
    }

    private void UpdateCompanyCard(string companyId)
    {
        var company = _companies.FirstOrDefault(c => c.ID == companyId);
        if (company == null)
            return;

        foreach (var (id, button) in _companyButtons)
        {
            button.Modulate = id == companyId ? Color.White : new Color(0.92f, 0.92f, 0.92f, 1f);
        }

        if (company.ID == "None")
        {
            CompanyDescriptionPanel.Visible = false;
            CompanyActionsPanel.Modulate = AvailableTint;
            RefreshActions();
            return;
        }

        CompanyDescriptionPanel.Visible = true;
        var isSelectable = _selectableCompanyIds.Contains(company.ID);
        var tint = isSelectable ? AvailableTint : LockedTint;
        CompanyDescriptionPanel.Modulate = tint;
        CompanyActionsPanel.Modulate = tint;

        var text = !string.IsNullOrEmpty(company.Description)
            ? Loc.GetString(company.Description)
            : Loc.GetString("company-none-description");

        CompanyDescription.SetMessage(text);
        RefreshActions();
    }

    private void RefreshActions()
    {
        var selected = _selectedCompanyId;
        JoinCompanyButton.Disabled = string.IsNullOrEmpty(selected)
            || selected == "None"
            || selected == _currentCompanyId
            || !_selectableCompanyIds.Contains(selected);

        LeaveCompanyButton.Disabled = _currentCompanyId == "None";
    }
}
