- type: department
  id: Empire
  name: department-Empire
  description: department-Empire-description
  color: "#ab7a52"
  weight: 50
  roles:
  - Praefect
  - Arbiter
  - Cardinal
  - Inquisitor
  - Consul
  - Praetorian
  - Auxilia
  - Neophyte
