# Empire department temporarily disabled with its jobs.
# - type: department
#   id: Empire
#   name: department-Empire
#   description: department-Empire-description
#   color: "#ab7a52"
#   weight: 50
#   roles:
#   - Praefect
#   - Arbiter
#   - Cardinal
#   - Inquisitor
#   - Consul
#   - Praetorian
#   - Auxilia
#   - Neophyte

- type: department
  id: Renegates
  name: department-Renegates
  description: department-Renegates-description
  color: "#111111"
  weight: 50
  roles:
  - Baron
  - Draftsman
  - Overseer
  - Quack
  - Foreman
  - Flunky
  
- type: department
  id: TSF
  name: department-TSF
  description: department-TSF-description
  color: "#2d6f9f"
  weight: 55
  roles:
  - TsfCommandingOfficer
  - TsfExecutiveOfficer
  - TsfSeniorOfficer
  - TsfSeniorAide
  - TsfAmbassador
  - TsfRanger
  - TsfRecruit
  - TsfEngineer