- type: job
  id: TsfBorg
  name: job-name-tsf-borg
  description: job-description-tsf-borg
  playTimeTracker: JobTsfBorg
  setPreference: false #Forge Change
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200
  assignedCompany: TSF
  canBeAntag: false
  hideConsoleVisibility: true #Forge Change
  icon: JobIconBorg
  supervisors: job-supervisors-hire
  jobEntity: PlayerBorgTSF
  applyTraits: false
