[game]
hostname = "[EN][MRP] Monolith | Inferno [EU West]"
desc = "A player-centric, ship-based, combat fork with a minimal ruleset. Featuring bluespace drives, ship artillery, autoloaders, shields, collisions, custom ships, companies, and original lore. Be sure to join our Discord!"
