[game]
soft_max_players = 100
lobbyduration = 180
lobbyenabled = true

[chat]
motd = "Welcome to Monolith! Your story takes place in the Colossus Sector. Be sure to join our Discord!"

[console]
login_host_user = "GoobStation"

[infolinks]
discord = "https://discord.gg/mxY4h2JuUw"
github = "https://github.com/Monolith-Station/Monolith"
appeal = "https://discord.gg/mxY4h2JuUw"

[admin]
new_player_join_sound = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
server_ban_erase_player = true
see_own_notes = true
show_pii_onban = true
admins_count_in_playercount = true
chat_discord_channel_id = 1379587459838640260
ahelp_discord_channel_id = 1379587501185962084
dead_chat_discord_channel_id = 1387956269351960726

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[biomass]
easy_mode = false

[ooc]
show_ooc_patron_color = false
discord_channel_id = 1331042209172164639

[shuttle]
auto_call_time = 360
mass_limit = 0

[surgery]
can_operate_on_self = true

[nf14.salvage]
expedition_rewards_enabled = true

[nf14.respawn]
time = 600

[hub]
advertise = 1
tags = "lang:en, rp:med, region:eu_w"
hub_urls = "https://hub.spacestation14.com/,https://hub.singularity14.co.uk/"

[auth]
mode = 1

[net]
tickrate = 30
max_connections = 2000
lidgren_log_warning = false
lidgren_log_error = false
log_late_msg = false

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 2
enabled = 0
