name: "Labels: Approved"

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    # Frontier: repo changed (space-wizards/space-station-14 < forge-station/monolith)
    if: ${{ (github.repository == 'forge-station/monolith') && (github.event.review.state == 'APPROVED') }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: checkUserMember
        run: |
          ROLE="${{ github.event.review.author_association }}"
          if [[ "$ROLE" == "MEMBER" || "$ROLE" == "OWNER" || "$ROLE" == "COLLABORATOR" ]]; then
            echo "is_authorized=true" >> $GITHUB_OUTPUT
          else
            echo "is_authorized=false" >> $GITHUB_OUTPUT
          fi

      - if: ${{ steps.checkUserMember.outputs.is_authorized == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Approved"
          
